name: sofiakb_elements
description: The packages allows to easily configure your project.
maintainer: Sofiane Akbly
version: 1.0.0-beta.3
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  phone_numbers_parser: ^7.0.0+1
  font_awesome_flutter:
    git:
      url: git@github.com:sofiakb/font_awesome_flutter.git
      ref: main

assets:
  - assets/
  - assets/img/

scripts:
  release: ./scripts/release.sh